{{- if or .Values.nats.leafnode.enabled .Values.nats.insecureWebsocket.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasmcloud_host.fullname" . }}
  labels:
    {{- include "wasmcloud_host.labels" . | nindent 4 }}
data:
  nats.conf: |-
    {{ if .Values.nats.leafnode.enabled -}}
    {{ if .Values.nats.jetstreamDomain -}}
    jetstream {
      domain: {{ .Values.nats.jetstreamDomain }}
    }
    {{- end }}
    leafnodes {
      remotes = [
        {
          url: {{ .Values.nats.leafnode.clusterURL | quote }}
          credentials: "/nats/nats.creds"
        },
      ]
    }
    {{- end }}
    {{- if and (not .Values.nats.leafnode.enabled) .Values.nats.insecureWebsocket.enabled -}}
    port: 4222
    monitor_port: 8222
    server_name: "wasmcloud"

    jetstream {}

    websocket {
      port: 4001
      no_tls: true
    }
    {{- end }}
{{- end }}
