{{- if .Values.wadm.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wadm
  labels:
    {{- include "wasmcloud_host.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wadm.replicas }}
  selector:
    matchLabels:
      {{- include "wadm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wadm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: wadm
          image: "{{ .Values.wadm.image.repository }}:{{ .Values.wadm.image.tag }}"
          imagePullPolicy: {{ .Values.wadm.image.pullPolicy }}
          env:
            - name: WADM_NATS_SERVER
              value: {{ .Values.wadm.natsServer | default (printf "%s:%v" (include "wasmcloud_host.fullname" .) (.Values.service.natsPort)) }}
          resources:
            {{- toYaml .Values.wadm.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.wadm.securityContext | nindent 12 }}
      {{- with .Values.wadm.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wadm.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wadm.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}